### ISSUE TITLE
AnimatedEditText only animates first character when using custom keyboard.

### ISSUE THREAD

**Issue by sjthn** [alphamu/AnimatedEditText#1]
HI. I have a problem with your AnimatedEditText. I ran your sample app on my phone having a custom keyboard(Swiftkey keyboard). When i started entering characters, only the first character gets animated.

I debugged and found that onTextChanged() method returns start value as always zero.

**Comment by alphamu** [comment]
Yes, that's a known issue. Swift or swiping effectively replace text which makes it a lot harder to figure out of the text is being added or not. Currently, I do plan to investigate if this is possible to solve. Will keep you posted.

**Comment by srijith14** [comment]
I have created a workaround which works when using Swiftkey keyboards, by finding the current position of the cursor.

**Comment by alphamu** [comment]
Fixed is version 0.0.4.
Swiping will animate text in.
Selecting words from auto suggest will animate in the word.
When typing with auto suggest, only the last character will animate, if you select a word to auto complete only the last character will animate.

**Comment by alphamu** [comment]
I've updated the comments above. However, this was actually fixed in v0.0.4. Seems that swift would add a space after auto complete and swiping where as the default keyboard adds the space when a new word is typed. Should work now.

**Comment by sjthn** [comment]
Great!. Will check it. Thanks.
